version: '3'

services:
   app:
      build: .
      ports:
         - "80:80"
      volumes:
         - ./src:/var/www/html
      environment:
         - MYSQL_SERVER=db
         - MYSQL_DATABASE
         - MYSQL_USER
         - MYSQL_PASSWORD
         - APP_ENV
      depends_on:
         - db
   db:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      volumes:
         - ./sql:/docker-entrypoint-initdb.d
         - db:/var/lib/mysql
      environment:
         - MYSQL_RANDOM_ROOT_PASSWORD=1
         - MYSQL_ONETIME_PASSWORD=1
         - MYSQL_DATABASE
         - MYSQL_USER
         - MYSQL_PASSWORD

volumes:
   db:
